"""initial schema

Revision ID: 79626e30ba81
Revises: 
Create Date: 2026-05-23 12:53:22.934316+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
import db.types

revision: str = '79626e30ba81'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('base_currency', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('initial_balance', db.types.DecimalText(), nullable=False),
    sa.Column('current_balance', db.types.DecimalText(), nullable=False),
    sa.Column('equity', db.types.DecimalText(), nullable=False),
    sa.Column('peak_nav', db.types.DecimalText(), nullable=False),
    sa.Column('created_at', db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_name'), ['name'], unique=True)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', db.types.UTCDateTime(), nullable=False),
    sa.Column('event_type', sa.Enum('SIGNAL_GENERATED', 'POSITION_OPENED', 'POSITION_CLOSED', 'STOP_UPDATED', 'CIRCUIT_BREAKER_TRIGGERED', 'LLM_CALL', 'MANUAL_ACTION', 'RESTART_RECOVERY', name='eventtype'), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_ts'), ['ts'], unique=False)

    op.create_table('signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', db.types.UTCDateTime(), nullable=False),
    sa.Column('bar_close_ts', db.types.UTCDateTime(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('source', sa.Enum('SCREENER', 'MANUAL', name='signalsource'), nullable=False),
    sa.Column('screener_score', sa.Integer(), nullable=True),
    sa.Column('confluence_score', sa.Float(), nullable=True),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', 'NO_TRADE', name='direction'), nullable=False),
    sa.Column('setup_intent_json', sa.JSON(), nullable=True),
    sa.Column('crypto_setup_json', sa.JSON(), nullable=True),
    sa.Column('decision', sa.Enum('TAKEN', 'SKIPPED_DEDUP', 'SKIPPED_SLOT', 'SKIPPED_DRAWDOWN', 'SKIPPED_FUNDING', 'NO_TRADE', name='decision'), nullable=False),
    sa.Column('decision_reason', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('strategy_version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'bar_close_ts', name='ux_signal_symbol_bar')
    )
    with op.batch_alter_table('signal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_ts'), ['ts'], unique=False)

    op.create_table('virtual_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='positionside'), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'CLOSED', name='positionstate'), nullable=False),
    sa.Column('entry_signal_id', sa.Integer(), nullable=False),
    sa.Column('entry_ts', db.types.UTCDateTime(), nullable=False),
    sa.Column('entry_price', db.types.DecimalText(), nullable=False),
    sa.Column('qty', db.types.DecimalText(), nullable=False),
    sa.Column('stop_price', db.types.DecimalText(), nullable=False),
    sa.Column('target_price', db.types.DecimalText(), nullable=False),
    sa.Column('exit_ts', db.types.UTCDateTime(), nullable=True),
    sa.Column('exit_price', db.types.DecimalText(), nullable=True),
    sa.Column('exit_reason', sa.Enum('STOP', 'TARGET', 'INVALIDATION', 'EXPIRED', 'MANUAL', 'EXTREME_FUNDING', 'DELISTED', name='exitreason'), nullable=True),
    sa.Column('realized_pnl', db.types.DecimalText(), nullable=True),
    sa.Column('simulated_fees', db.types.DecimalText(), nullable=True),
    sa.Column('simulated_funding', db.types.DecimalText(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['entry_signal_id'], ['signal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('virtual_position', schema=None) as batch_op:
        batch_op.create_index('ix_position_state', ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_position_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ux_position_open_per_symbol', ['account_id', 'symbol'], unique=True, sqlite_where=sa.text("state = 'OPEN'"), postgresql_where=sa.text("state = 'OPEN'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_position', schema=None) as batch_op:
        batch_op.drop_index('ux_position_open_per_symbol', sqlite_where=sa.text("state = 'OPEN'"), postgresql_where=sa.text("state = 'OPEN'"))
        batch_op.drop_index(batch_op.f('ix_virtual_position_account_id'))
        batch_op.drop_index('ix_position_state')

    op.drop_table('virtual_position')
    with op.batch_alter_table('signal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_ts'))
        batch_op.drop_index(batch_op.f('ix_signal_symbol'))

    op.drop_table('signal')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_ts'))
        batch_op.drop_index(batch_op.f('ix_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_entity_type'))
        batch_op.drop_index(batch_op.f('ix_event_entity_id'))

    op.drop_table('event')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_name'))

    op.drop_table('account')
    # ### end Alembic commands ###
