"""initial schema

Revision ID: dcdf77794a05
Revises: 
Create Date: 2026-05-26 15:44:37.472702+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
import db.types

revision: str = 'dcdf77794a05'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('base_currency', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('initial_balance', db.types.DecimalText(), nullable=False),
    sa.Column('current_balance', db.types.DecimalText(), nullable=False),
    sa.Column('equity', db.types.DecimalText(), nullable=False),
    sa.Column('peak_nav', db.types.DecimalText(), nullable=False),
    sa.Column('created_at', db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_name'), 'account', ['name'], unique=True)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', db.types.UTCDateTime(), nullable=False),
    sa.Column('event_type', sa.Enum('SIGNAL_GENERATED', 'POSITION_OPENED', 'POSITION_CLOSED', 'STOP_UPDATED', 'CIRCUIT_BREAKER_TRIGGERED', 'LLM_CALL', 'MANUAL_ACTION', 'RESTART_RECOVERY', name='eventtype'), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_entity_id'), 'event', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_entity_type'), 'event', ['entity_type'], unique=False)
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_ts'), 'event', ['ts'], unique=False)
    op.create_table('signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', db.types.UTCDateTime(), nullable=False),
    sa.Column('bar_close_ts', db.types.UTCDateTime(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('source', sa.Enum('SCREENER', 'MANUAL', name='signalsource'), nullable=False),
    sa.Column('screener_score', sa.Integer(), nullable=True),
    sa.Column('confluence_score', sa.Float(), nullable=True),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', 'NO_TRADE', name='direction'), nullable=False),
    sa.Column('setup_intent_json', sa.JSON(), nullable=True),
    sa.Column('crypto_setup_json', sa.JSON(), nullable=True),
    sa.Column('decision', sa.Enum('TAKEN', 'SKIPPED_DEDUP', 'SKIPPED_SLOT', 'SKIPPED_DRAWDOWN', 'SKIPPED_FUNDING', 'NO_TRADE', name='decision'), nullable=False),
    sa.Column('decision_reason', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('strategy_version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'bar_close_ts', name='ux_signal_symbol_bar')
    )
    op.create_index(op.f('ix_signal_symbol'), 'signal', ['symbol'], unique=False)
    op.create_index(op.f('ix_signal_ts'), 'signal', ['ts'], unique=False)
    op.create_table('system_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('halted', sa.Boolean(), nullable=False),
    sa.Column('halt_reason', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('updated_at', db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virtual_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='positionside'), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'CLOSED', name='positionstate'), nullable=False),
    sa.Column('entry_signal_id', sa.Integer(), nullable=False),
    sa.Column('entry_ts', db.types.UTCDateTime(), nullable=False),
    sa.Column('entry_price', db.types.DecimalText(), nullable=False),
    sa.Column('qty', db.types.DecimalText(), nullable=False),
    sa.Column('notional', db.types.DecimalText(), nullable=True),
    sa.Column('stop_price', db.types.DecimalText(), nullable=False),
    sa.Column('target_price', db.types.DecimalText(), nullable=False),
    sa.Column('exit_ts', db.types.UTCDateTime(), nullable=True),
    sa.Column('exit_price', db.types.DecimalText(), nullable=True),
    sa.Column('exit_reason', sa.Enum('STOP', 'TARGET', 'INVALIDATION', 'EXPIRED', 'MANUAL', 'EXTREME_FUNDING', 'DELISTED', name='exitreason'), nullable=True),
    sa.Column('realized_pnl', db.types.DecimalText(), nullable=True),
    sa.Column('simulated_fees', db.types.DecimalText(), nullable=True),
    sa.Column('simulated_funding', db.types.DecimalText(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['entry_signal_id'], ['signal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_position_state', 'virtual_position', ['state'], unique=False)
    op.create_index(op.f('ix_virtual_position_account_id'), 'virtual_position', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_position_account_id'), table_name='virtual_position')
    op.drop_index('ix_position_state', table_name='virtual_position')
    op.drop_table('virtual_position')
    op.drop_table('system_state')
    op.drop_index(op.f('ix_signal_ts'), table_name='signal')
    op.drop_index(op.f('ix_signal_symbol'), table_name='signal')
    op.drop_table('signal')
    op.drop_index(op.f('ix_event_ts'), table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_entity_type'), table_name='event')
    op.drop_index(op.f('ix_event_entity_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_account_name'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
